export type PortfolioProject = {
  id: string;
  title: string;
  category: "ai" | "fullstack" | "interface";
  categoryLabel: string;
  description: string;
  stack: string[];
  features: string[];
  sourceUrl?: string;
  liveUrl?: string;
  image?: string;
  icon?: string;
  logo?: string;
  logoDark?: boolean;
  diagram: string[];
  year: string;
  demoNote?: string;
  archiveNote?: string;
};

// Project implementation details come from the linked public repositories.
// Employment, dates, and professional skills come from the supplied resume.
export const portfolioProjects: PortfolioProject[] = [
  {
    id: "grounded-notes",
    logo: "/project-logos/grounded-notes.svg",
    icon: "/artwork/learning-book.png",
    title: "Grounded Notes",
    category: "ai",
    categoryLabel: "AI · RETRIEVAL & Q&A",
    year: "2026",
    description:
      "A local Q&A assistant that retrieves passages from Markdown notes and generates Ollama answers with source citations.",
    stack: ["TypeScript", "React", "Express", "SQLite", "Ollama"],
    features: [
      "Markdown ingestion, chunking, and TF-IDF passage retrieval",
      "Source citations and low-match refusal before generation",
      "Admin ingestion tools and automated evaluation cases",
    ],
    sourceUrl: "https://github.com/Suraj1812/grounded-notes-qa-assistant",
    image: "/projects/grounded-notes.png",
    diagram: ["Markdown notes", "Passage retrieval", "Ollama + citations"],
  },
  {
    id: "local-agent",
    icon: "/artwork/ai-robot.png",
    title: "Local Agent",
    category: "ai",
    categoryLabel: "AI · AGENT WORKFLOWS",
    year: "2026",
    description:
      "An agent application combining planning, tool execution, and persistent memory with a Next.js interface and a FastAPI backend.",
    stack: ["Next.js", "FastAPI", "SQLite", "SQLAlchemy"],
    features: [
      "Planner and manager modules coordinate agent tasks",
      "Tool execution and stored conversational memory",
      "A typed frontend connected to a Python service layer",
    ],
    sourceUrl: "https://github.com/Suraj1812/Local-Agent",
    diagram: ["Plan a task", "Execute tools", "Persist memory"],
    demoNote: "Source available · local model setup",
  },
  {
    id: "aipedia",
    logo: "/project-logos/aipedia.svg",
    icon: "/artwork/learning-book.png",
    title: "AIPedia",
    category: "ai",
    categoryLabel: "AI · CONTEXTUAL LEARNING",
    year: "2026",
    description:
      "An AI learning application that connects topic context and a JavaScript interface to a Node.js API and local Ollama models.",
    stack: ["Node.js", "JavaScript", "Ollama"],
    features: [
      "Ollama chat integration through a server API",
      "Topic-specific local context for responses",
      "URL learning to extend the application's knowledge",
    ],
    sourceUrl: "https://github.com/Suraj1812/AIpedia",
    diagram: ["Topic context", "Node.js API", "Ollama response"],
    demoNote: "Source available · hosted demo offline",
  },
  {
    id: "chatapp",
    icon: "/artwork/backend-database.png",
    title: "Realtime Chat App",
    category: "fullstack",
    categoryLabel: "FULL-STACK · REALTIME",
    year: "2025",
    description:
      "A database-backed messaging application with real-time events, an Express backend, and a responsive conversation interface.",
    stack: ["Node.js", "Express", "Socket.IO", "SQLite"],
    features: [
      "Socket.IO events support real-time conversations",
      "Express service layer with SQLite persistence",
      "Responsive messaging views and interaction states",
    ],
    sourceUrl: "https://github.com/Suraj1812/ChatApp",
    diagram: ["Conversation UI", "Socket.IO events", "SQLite persistence"],
    demoNote: "Source available · hosted demo offline",
  },
  {
    id: "solar-system",
    logo: "/project-logos/solar-system.png",
    icon: "/artwork/planet-3d.png",
    title: "Solar System Explorer",
    category: "interface",
    categoryLabel: "INTERACTIVE · 3D & MOTION",
    year: "2025",
    description:
      "An interactive solar-system experience built with React, Three.js, and motion to make planetary exploration visual and engaging.",
    stack: ["React", "Three.js", "GSAP", "Vite"],
    features: [
      "Three.js scenes for planetary exploration",
      "Motion and transitions using GSAP and Framer Motion",
      "Responsive React components for the interactive experience",
    ],
    sourceUrl: "https://github.com/Suraj1812/The-Solar-System",
    liveUrl: "https://the-solar-system-six.vercel.app/",
    diagram: ["React interface", "Three.js scenes", "Motion & exploration"],
  },
  {
    id: "dattamsha",
    logo: "/project-logos/dattamsha.png",
    icon: "/artwork/analytics-monitor.png",
    title: "Dattamsha Data Labs",
    category: "fullstack",
    categoryLabel: "FULL-STACK · BUSINESS WEB",
    year: "2025",
    description:
      "A business website pairing a React and TypeScript interface with an Express backend and reusable motion components.",
    stack: ["React", "TypeScript", "Express", "Framer Motion"],
    features: [
      "React and Vite frontend with typed components",
      "Express backend for application services",
      "Reusable interface sections and Framer Motion interactions",
    ],
    sourceUrl: "https://github.com/Suraj1812/Dattamsha-Data-Labs",
    liveUrl: "https://dattamsha-data-labs.vercel.app/",
    image: "/projects/dattamsha.png",
    diagram: ["React + TypeScript", "Express services", "Business interface"],
  },
  {
    id: "cricket-connect-ai",
    logo: "/project-logos/cricket-connect-ai.png",
    icon: "/artwork/analytics-monitor.png",
    title: "Cricket Connect AI",
    category: "interface",
    categoryLabel: "CLIENT WEB · SPORTS INTELLIGENCE",
    year: "2026",
    description:
      "A cricket intelligence product website with clear paths for fan insights and professional performance analysis.",
    stack: ["Product UI", "Data storytelling", "Responsive web"],
    features: [
      "Distinct product paths for fans and professionals",
      "Clear presentation of contextual cricket analysis",
      "Responsive content hierarchy and product navigation",
    ],
    liveUrl: "https://cricketconnect.ai/",
    image: "/projects/cricket-connect.png",
    diagram: ["Product story", "Audience paths", "Responsive interface"],
  },
  {
    id: "fashion-pattern-lab",
    logo: "/project-logos/fashion-pattern-lab.png",
    icon: "/artwork/commerce-bag.png",
    title: "Fashion Pattern Lab",
    category: "interface",
    categoryLabel: "CLIENT WEB · LEARNING & COMMERCE",
    year: "2026",
    description:
      "A specialist learning and commerce website connecting pattern-making courses, digital patterns, and custom services.",
    stack: ["Course discovery", "Digital commerce", "Responsive UI"],
    features: [
      "Clear routes to courses, digital patterns, and services",
      "Educational content for a specialist audience",
      "Content structure connecting learning to practical products",
    ],
    liveUrl: "https://fashionpatternlab.com/",
    image: "/projects/fashion-pattern-lab.png",
    diagram: ["Learning content", "Course discovery", "Digital patterns"],
  },
  {
    id: "wildverse",
    icon: "/artwork/browser-ui.png",
    title: "Wildverse",
    category: "interface",
    categoryLabel: "CREATIVE WEB · MOTION",
    year: "2025",
    description:
      "An expressive interface experiment built around animated cards, visual storytelling, and editorial layouts.",
    stack: ["Next.js", "React", "TypeScript", "Framer Motion", "GSAP"],
    features: [
      "Animated interface components and motion sequences",
      "Expressive card compositions and visual hierarchy",
      "Responsive layouts built with React and Next.js",
    ],
    sourceUrl: "https://github.com/Suraj1812/wildverse",
    liveUrl: "https://wildverse-theta.vercel.app/",
    diagram: ["Editorial layout", "Animated cards", "Visual storytelling"],
  },
  {
    id: "brutal-design",
    logo: "/project-logos/brutal-design.svg",
    icon: "/artwork/browser-ui.png",
    title: "Brutal Design",
    category: "interface",
    categoryLabel: "UI EXPERIMENT · BOLD DESIGN",
    year: "2025",
    description:
      "A web interface exploring bold typography, contrasting colors, and playful interaction patterns.",
    stack: ["Next.js", "React", "TypeScript", "Tailwind CSS", "Motion"],
    features: [
      "High-contrast layouts and large typography",
      "Reusable UI components with interactive states",
      "Motion and responsive layout exploration",
    ],
    sourceUrl: "https://github.com/Suraj1812/BrutalDesign",
    liveUrl: "https://brutal-design.vercel.app/",
    diagram: ["Bold type", "Interaction states", "Responsive system"],
  },
  {
    id: "amze",
    icon: "/artwork/commerce-bag.png",
    title: "AMZE",
    category: "interface",
    categoryLabel: "COMMERCE · ARCHIVED PROJECT",
    year: "2026",
    description:
      "A technology storefront organized around category browsing, product discovery, and buying support.",
    stack: ["E-commerce", "Product discovery", "Responsive UI"],
    features: [
      "Category-led browsing across technology products",
      "Product rails and navigation for catalogue discovery",
      "Support and delivery information near the buying path",
    ],
    image: "/amze-store-banner.png",
    diagram: ["Category browsing", "Product discovery", "Buying support"],
    archiveNote: "Archived project · the public site is currently unavailable",
  },
  {
    id: "bolo",
    logo: "/project-logos/bolo.svg",
    image: "/projects/bolo.png",
    title: "Bolo",
    category: "interface",
    categoryLabel: "VOICE · BROWSER WORKSPACE",
    year: "2026",
    description:
      "A browser voice workspace for speech recognition, editable transcripts, and text-to-speech playback.",
    stack: ["Next.js", "React", "TypeScript", "Web Speech API", "Tailwind CSS"],
    features: [
      "Speech recognition and playback",
      "Language and voice selection",
      "Locally saved transcripts and preferences",
    ],
    sourceUrl: "https://github.com/Suraj1812/Bolo",
    liveUrl: "https://bolo-voice.vercel.app",
    icon: "/artwork/voice-mic.png",
    diagram: ["Voice input", "Editable transcript", "Speech playback"],
  },
  {
    id: "filer",
    logo: "/project-logos/filer.svg",
    title: "Filer",
    category: "fullstack",
    categoryLabel: "FULL-STACK · DRIVE WORKSPACE",
    year: "2026",
    description:
      "An authenticated Google Drive file manager for searching, uploading, organizing, and sharing files.",
    stack: [
      "Next.js",
      "TypeScript",
      "Google Drive API",
      "Auth.js",
      "Prisma",
      "PostgreSQL",
    ],
    features: [
      "Google OAuth and Drive integration",
      "Folder, upload, move, and sharing routes",
      "Database-backed user and application settings",
    ],
    sourceUrl: "https://github.com/Suraj1812/Filer",
    liveUrl: "https://filer-three.vercel.app",
    icon: "/artwork/cloud-files.png",
    demoNote: "Google sign-in required",
    diagram: ["Google sign-in", "Drive API", "File workspace"],
  },
  {
    id: "flyjustice-lite",
    logo: "/project-logos/flyjustice-lite.png",
    title: "FlyJustice Lite",
    category: "fullstack",
    categoryLabel: "FULL-STACK · CLAIM MANAGEMENT",
    year: "2026",
    description:
      "A Razor Pages application with document uploads, claim tracking, and administrative review.",
    stack: [
      "C#",
      "ASP.NET Core",
      "Razor Pages",
      "Entity Framework Core",
      "SQL Server",
    ],
    features: [
      "Claim submission and document uploads",
      "Rule-based compensation estimates",
      "Claim tracking and administrative review",
    ],
    sourceUrl: "https://github.com/Suraj1812/FlyJustice-Lite",
    icon: "/artwork/legal-gavel.png",
    diagram: ["Submit claim", "Review documents", "Track progress"],
  },
  {
    id: "sync",
    title: "Sync",
    category: "fullstack",
    categoryLabel: "FULL-STACK · MESSAGING & VIDEO",
    year: "2026",
    description:
      "A communication application combining one-to-one video calls, real-time messaging, and saved conversations.",
    stack: [
      "React",
      "TypeScript",
      "NestJS",
      "PostgreSQL",
      "Socket.IO",
      "WebRTC",
    ],
    features: [
      "Real-time messaging",
      "WebRTC video call flows",
      "JWT authentication and Prisma persistence",
    ],
    sourceUrl: "https://github.com/Suraj1812/Sync",
    icon: "/artwork/backend-database.png",
    diagram: ["Connect users", "Exchange messages", "WebRTC calls"],
  },
  {
    id: "visionplay",
    logo: "/project-logos/visionplay.svg",
    title: "VisionPlay",
    category: "ai",
    categoryLabel: "AI · COMPUTER VISION",
    year: "2026",
    description:
      "A video-analysis workspace with object detection, tracking, visual overlays, and structured processing results.",
    stack: ["Python", "FastAPI", "React", "OpenCV", "YOLO"],
    features: [
      "YOLO detection and object tracking",
      "Video processing and overlay playback",
      "API-backed sessions and analysis results",
    ],
    sourceUrl: "https://github.com/Suraj1812/VisionPlay",
    icon: "/artwork/analytics-monitor.png",
    diagram: ["Video input", "Detect & track", "Analysis results"],
  },
  {
    id: "maidan",
    title: "Maidan",
    category: "fullstack",
    categoryLabel: "FULL-STACK · CAMPUS CHALLENGES",
    year: "2026",
    description:
      "A campus challenge platform with squads, invitations, evidence submission, and community rankings.",
    stack: ["Next.js", "React", "TypeScript", "Supabase", "Tailwind CSS"],
    features: [
      "Squad creation and member invitations",
      "Challenges and evidence submission",
      "Leaderboards, notifications, and moderation",
    ],
    sourceUrl: "https://github.com/Suraj1812/Maidan",
    icon: "/artwork/learning-book.png",
    diagram: ["Build a squad", "Join a challenge", "Submit evidence"],
  },
  {
    id: "navapur",
    logo: "/project-logos/navapur.svg",
    image: "/projects/navapur.png",
    title: "Navapur",
    category: "interface",
    categoryLabel: "INTERACTIVE · 3D CITY",
    year: "2026",
    description:
      "An explorable 3D city with a controllable player, simulated residents, traffic, and adaptive graphics quality.",
    stack: ["TypeScript", "Three.js", "Vite", "WebGL"],
    features: [
      "3D city and player controls",
      "Resident and traffic simulation",
      "Adaptive quality and saved progress",
    ],
    sourceUrl: "https://github.com/Suraj1812/Navapur",
    liveUrl: "https://navapur.vercel.app",
    icon: "/artwork/game-controller.png",
    diagram: ["Explore city", "Simulate residents", "Interact & play"],
  },
  {
    id: "3d-cricket",
    logo: "/project-logos/3d-cricket.svg",
    image: "/projects/3d-cricket.png",
    title: "3D Cricket",
    category: "interface",
    categoryLabel: "INTERACTIVE · 3D GAME",
    year: "2026",
    description:
      "A browser batting game with 3D field scenes, shot timing and placement, scoring, and multiple match formats.",
    stack: ["React", "Three.js", "React Three Fiber", "Zustand", "Vite"],
    features: [
      "Interactive batting and fielding flows",
      "Scoring, wickets, and match formats",
      "Keyboard and touch controls",
    ],
    sourceUrl: "https://github.com/Suraj1812/3D-Cricket",
    liveUrl: "https://3d-cricket.vercel.app",
    icon: "/artwork/game-controller.png",
    diagram: ["Time the shot", "Choose placement", "Score runs"],
  },
  {
    id: "earthre-sla-monitor",
    logo: "/project-logos/earthre-sla-monitor.svg",
    title: "Earthre SLA Monitor",
    category: "fullstack",
    categoryLabel: "FULL-STACK · SERVICE MONITORING",
    year: "2026",
    description:
      "An operational dashboard that imports service-check CSVs and summarizes uptime, latency, and SLA performance.",
    stack: ["React", "TypeScript", "Cloudflare D1", "SQL", "Recharts"],
    features: [
      "CSV validation and duplicate detection",
      "Uptime and latency summaries",
      "Date filters, paginated logs, and upload history",
    ],
    sourceUrl: "https://github.com/Suraj1812/earthre-sla-monitor",
    icon: "/artwork/analytics-monitor.png",
    diagram: ["Import CSV", "Aggregate checks", "Monitor service"],
  },
  {
    id: "ledgent-ai",
    logo: "/project-logos/ledgent-ai.svg",
    title: "Ledgent.AI",
    category: "ai",
    categoryLabel: "AI · FINANCE WORKFLOWS",
    year: "2026",
    description:
      "An accounts-payable workspace with invoice matching, exception review, approval workflows, and an optional OpenAI copilot.",
    stack: ["React", "NestJS", "TypeScript", "Prisma", "PostgreSQL", "OpenAI"],
    features: [
      "Rule-based invoice and purchase-order matching",
      "Exception review, approvals, and audit records",
      "Optional OpenAI copilot",
    ],
    sourceUrl: "https://github.com/Suraj1812/Ledgent.AI",
    icon: "/artwork/automation-gears.png",
    diagram: ["Match invoice", "Review exceptions", "Approve payment"],
  },
  {
    id: "sasta-ai",
    logo: "/project-logos/sasta-ai.svg",
    title: "Sasta AI",
    category: "ai",
    categoryLabel: "AI · SOURCE-LINKED RESEARCH",
    year: "2026",
    description:
      "A source-linked research assistant with web excerpts, contextual follow-ups, relevant images, and optional model synthesis.",
    stack: ["Next.js", "TypeScript", "FastAPI", "Python", "OpenAI"],
    features: [
      "Source-linked excerpts and relevant images",
      "Conversation context for follow-up questions",
      "Keyless retrieval with optional OpenAI synthesis",
    ],
    sourceUrl: "https://github.com/Suraj1812/SastaAI",
    icon: "/artwork/ai-robot.png",
    diagram: ["Research question", "Retrieve sources", "Linked response"],
    demoNote: "Source available · default answers are extractive",
  },
  {
    id: "webintel",
    logo: "/project-logos/webintel.svg",
    title: "WebIntel",
    category: "ai",
    categoryLabel: "AI · WEBSITE INTELLIGENCE",
    year: "2026",
    description:
      "A website research workspace combining browser scraping, saved reports, SEO observations, and optional AI business insights.",
    stack: [
      "Next.js",
      "TypeScript",
      "FastAPI",
      "Playwright",
      "Prisma",
      "PostgreSQL",
    ],
    features: [
      "Browser screenshots and page-content extraction",
      "Saved reports, scorecards, and comparison routes",
      "Optional OpenAI insights with heuristic fallback",
    ],
    sourceUrl: "https://github.com/Suraj1812/WebIntel",
    icon: "/artwork/browser-ui.png",
    diagram: ["Website URL", "Scrape and analyze", "Saved report"],
    demoNote: "Source available",
  },
  {
    id: "ai-concierge",
    title: "AI Concierge",
    category: "ai",
    categoryLabel: "AI · OPERATIONS AUTOMATION",
    year: "2026",
    description:
      "A concierge backend connecting customer requests, structured AI extraction, vendor quotes, proposals, payments, and bookings.",
    stack: ["TypeScript", "Express", "OpenAI", "MongoDB", "Redis", "BullMQ"],
    features: [
      "WhatsApp and email request-processing workflows",
      "OpenAI extraction, quote normalization, and proposal copy",
      "PDF proposals, Razorpay orders, and queued follow-ups",
    ],
    sourceUrl: "https://github.com/Suraj1812/concierge-automation",
    icon: "/artwork/automation-gears.png",
    diagram: ["Customer request", "Vendor proposal", "Payment and booking"],
    demoNote: "Source available · backend API and worker",
  },
  {
    id: "svastra",
    title: "Svastra+",
    category: "fullstack",
    categoryLabel: "FULL-STACK · CARE WORKFLOWS",
    year: "2026",
    description:
      "A care-workflow demonstrator connecting patient consent, provider care plans, scheduled tasks, responses, and rule-based alerts.",
    stack: ["React", "TypeScript", "FastAPI", "Python", "SQLAlchemy", "SQLite"],
    features: [
      "Consent-backed patient and provider relationships",
      "Care plans, scheduled tasks, and patient responses",
      "Role-scoped event monitoring and audit history",
    ],
    sourceUrl: "https://github.com/Suraj1812/Svastra",
    icon: "/artwork/backend-database.png",
    diagram: [
      "Consent and care plan",
      "Scheduled tasks",
      "Responses and alerts",
    ],
    demoNote: "Source available · workflow demonstrator",
  },
  {
    id: "mini-llm",
    title: "Mini LLM",
    category: "ai",
    categoryLabel: "AI · MODEL TRAINING",
    year: "2026",
    description:
      "A small GPT-style language-model training lab with a web interface for custom-text training and text generation.",
    stack: ["Python", "PyTorch", "FastAPI", "Tokenizers", "JavaScript"],
    features: [
      "Causal attention and transformer blocks in PyTorch",
      "Custom-text training and generation APIs",
      "Training progress and saved model artifacts",
    ],
    sourceUrl: "https://github.com/Suraj1812/Mini-LLM",
    icon: "/artwork/ai-robot.png",
    diagram: ["Custom training text", "PyTorch transformer", "Generated text"],
    demoNote: "Source available · small experimental model",
  },
  {
    id: "vacati-console",
    logo: "/project-logos/vacati-console.png",
    title: "Vacati Intelligence Console",
    category: "ai",
    categoryLabel: "AI · DOCUMENT RETRIEVAL",
    year: "2026",
    description:
      "A hospitality knowledge console with document ingestion, hybrid retrieval, streamed answers, and source citations.",
    stack: [
      "Next.js",
      "TypeScript",
      "LangChain",
      "Ollama",
      "PostgreSQL",
      "pgvector",
    ],
    features: [
      "Document chunking and embedding ingestion",
      "Semantic and lexical retrieval with source attribution",
      "Streaming provider adapters and local or pgvector storage",
    ],
    sourceUrl: "https://github.com/Suraj1812/Vacati-Intelligence-Console",
    icon: "/artwork/cloud-files.png",
    diagram: ["Upload documents", "Hybrid retrieval", "Answer with citations"],
    demoNote: "Source available · configurable model providers",
  },
  {
    id: "resume-extractor",
    logo: "/project-logos/resume-extractor.svg",
    title: "Resume Extractor",
    category: "ai",
    categoryLabel: "AI · DOCUMENT EXTRACTION",
    year: "2026",
    description:
      "A resume-processing app that extracts structured fields from uploaded documents into an editable form.",
    stack: [
      "Next.js",
      "TypeScript",
      "FastAPI",
      "Python",
      "PyTorch",
      "Transformers",
    ],
    features: [
      "PDF, DOCX, and text document parsing",
      "Transformer NER with rule-based extraction fallbacks",
      "Structured profile fields and editable result forms",
    ],
    sourceUrl: "https://github.com/Suraj1812/Resume-Extractor",
    icon: "/artwork/cloud-files.png",
    diagram: [
      "Upload resume",
      "Extract structured fields",
      "Review editable form",
    ],
    demoNote: "Source available",
  },
  {
    id: "axe",
    logo: "/project-logos/axe.svg",
    title: "Axe",
    category: "fullstack",
    categoryLabel: "FULL-STACK · 3D EDITOR",
    year: "2026",
    description:
      "A 3D web-scene editor with object controls, animation keyframes, interface blocks, and saved projects.",
    stack: [
      "Next.js",
      "Three.js",
      "React Three Fiber",
      "Zustand",
      "Express",
      "MongoDB",
    ],
    features: [
      "Interactive scene hierarchy and object properties",
      "Animation timeline, interface blocks, and undo history",
      "Project persistence with MongoDB or local JSON storage",
    ],
    sourceUrl: "https://github.com/Suraj1812/Axe",
    icon: "/artwork/planet-3d.png",
    diagram: ["Compose scene", "Animate objects", "Save project"],
    demoNote: "Source available",
  },
  {
    id: "spendwise",
    title: "SpendWise",
    category: "fullstack",
    categoryLabel: "FULL-STACK · MOBILE FINANCE",
    year: "2026",
    description:
      "A mobile expense tracker with budget progress, expense history, category insights, and an Express API.",
    stack: ["React Native", "Expo", "TypeScript", "Express", "Zustand", "Zod"],
    features: [
      "Expense creation, editing, search, and filtering",
      "Budget progress and category or monthly insights",
      "Authenticated API, local file persistence, and CSV export",
    ],
    sourceUrl: "https://github.com/Suraj1812/SpendWise",
    icon: "/artwork/backend-database.png",
    diagram: ["Record expenses", "Track budget", "Explore insights"],
    demoNote: "Source available · mobile application",
  },
  {
    id: "instagram-mobile",
    title: "Instagram-style Mobile App",
    category: "fullstack",
    categoryLabel: "MOBILE · SOCIAL PLATFORM",
    year: "2026",
    description:
      "A mobile social application with image and video posts, discovery feeds, profiles, and Supabase-backed authentication and media.",
    stack: ["React Native", "Expo", "TypeScript", "Supabase", "Zustand"],
    features: [
      "Feed, explore, reels, and saved-post views",
      "Supabase authentication and RPC-backed repositories",
      "Image processing and media uploads to storage",
    ],
    sourceUrl: "https://github.com/Suraj1812/Instagram",
    icon: "/artwork/browser-ui.png",
    diagram: ["Create media", "Publish and discover", "Social interactions"],
    demoNote: "Source available · mobile application",
    logo: "/project-logos/instagram-mobile.png",
  },
  {
    id: "shot-explorer",
    title: "Shot Explorer",
    category: "ai",
    categoryLabel: "AI · IMAGE WORKSPACE",
    year: "2026",
    description:
      "An image-framing workspace with pan and zoom controls, saved results, and optional Gemini image generation.",
    stack: ["React", "JavaScript", "Vite", "Gemini", "Canvas API"],
    features: [
      "Reference-image upload and framing controls",
      "Optional server-side Gemini generation",
      "Local canvas previews, favorites, and downloads",
    ],
    sourceUrl: "https://github.com/Suraj1812/shot-explorer-app",
    icon: "/artwork/browser-ui.png",
    diagram: ["Reference image", "Frame or generate", "Save and download"],
    demoNote: "Source available · local preview fallback",
  },
  {
    id: "chadwallet",
    title: "ChadWallet",
    category: "interface",
    categoryLabel: "INTERFACE · TRADING PREVIEW",
    year: "2026",
    description:
      "A Solana token research and trading-interface prototype with token detail pages, charts, and buy or sell quote previews.",
    stack: ["Next.js", "React", "TypeScript", "Privy", "BirdEye API"],
    features: [
      "Searchable token lists and token detail pages",
      "Optional BirdEye market data with demo fallback",
      "Buy and sell quote preview interface",
    ],
    sourceUrl: "https://github.com/Suraj1812/ChadWallet",
    icon: "/artwork/backend-database.png",
    diagram: ["Discover tokens", "Inspect market data", "Preview a quote"],
    demoNote: "Source available · transaction execution is not implemented",
    logo: "/project-logos/chadwallet.png",
    logoDark: true,
  },
  {
    id: "indian-tourism",
    title: "Indian Tourism DB",
    category: "fullstack",
    categoryLabel: "FULL-STACK · PLACE DISCOVERY",
    year: "2026",
    description:
      "A tourism search application with indexed place records, map exploration, source links, and Wikipedia enrichment.",
    stack: ["JavaScript", "Express", "EJS", "FlexSearch", "Leaflet", "Zod"],
    features: [
      "Indexed place search and category filters",
      "Interactive map markers and place detail views",
      "Validated saved records and Wikipedia enrichment",
    ],
    sourceUrl: "https://github.com/Suraj1812/Indian-Tourism",
    icon: "/artwork/browser-ui.png",
    diagram: ["Search places", "Explore map", "Read sourced details"],
    demoNote: "Source available",
  },
  {
    id: "gb-orderflow",
    title: "GB OrderFlow",
    category: "fullstack",
    categoryLabel: "FULL-STACK · DEALER OPERATIONS",
    year: "2026",
    description:
      "A dealer-ordering workspace with catalogue selection, head-office approval, and structured export workflows.",
    stack: ["React", "TypeScript", "Express", "Prisma", "PostgreSQL", "MUI"],
    features: [
      "Dealer catalogue and validated order submission",
      "Head-office order approval and rejection",
      "Deterministic CSV exports and export history",
    ],
    sourceUrl: "https://github.com/Suraj1812/GB-OrderFlow",
    icon: "/artwork/automation-gears.png",
    diagram: ["Dealer order", "Office approval", "CSV export"],
    demoNote: "Source available",
    logo: "/project-logos/gb-orderflow.svg",
  },
  {
    id: "draw-clash",
    title: "Draw Clash",
    category: "fullstack",
    categoryLabel: "REALTIME · MULTIPLAYER GAME",
    year: "2026",
    description:
      "A multiplayer drawing-and-guessing game with synchronized canvas strokes, live chat, private rooms, and turn-based scoring.",
    stack: ["React", "TypeScript", "Express", "Socket.IO", "Canvas API"],
    features: [
      "Synchronized drawing tools and canvas events",
      "Public matchmaking and private room codes",
      "Live guesses, rotating turns, and speed-based scores",
    ],
    sourceUrl: "https://github.com/Suraj1812/Guess-Where",
    icon: "/artwork/game-controller.png",
    diagram: ["Join room", "Draw and guess", "Score the round"],
    demoNote: "Source available · repository named Guess-Where",
  },
  {
    id: "fomio",
    title: "Fomio",
    category: "fullstack",
    categoryLabel: "FULL-STACK · SOCIAL WEB",
    year: "2026",
    description:
      "A social web application with user profiles, paginated feeds, posts, comments, follows, and image uploads.",
    stack: [
      "Next.js",
      "TypeScript",
      "Prisma",
      "PostgreSQL",
      "Auth.js",
      "Cloudinary",
    ],
    features: [
      "Global and following feeds with cursor pagination",
      "Post creation, likes, comments, and profile routes",
      "Authenticated image uploads and email verification flows",
    ],
    sourceUrl: "https://github.com/Suraj1812/fomio",
    icon: "/artwork/browser-ui.png",
    diagram: ["User profile", "Publish a post", "Feed and interactions"],
    demoNote: "Source available",
    logo: "/project-logos/fomio.png",
  },
  {
    id: "conversionlens",
    title: "ConversionLens / Shoplytics",
    category: "fullstack",
    categoryLabel: "FULL-STACK · COMMERCE ANALYTICS",
    year: "2026",
    description:
      "A commerce analytics application that collects storefront events and displays conversion funnels and product performance.",
    stack: [
      "React",
      "JavaScript",
      "Express",
      "PostgreSQL",
      "Shopify Custom Pixel",
    ],
    features: [
      "Product-view, cart, and purchase event ingestion",
      "Event deduplication and PostgreSQL persistence",
      "Time-filtered funnel and product analytics",
    ],
    sourceUrl: "https://github.com/Suraj1812/ConversionLens",
    icon: "/artwork/backend-database.png",
    diagram: [
      "Storefront events",
      "Persist and aggregate",
      "Analytics dashboard",
    ],
    demoNote: "Source available",
    logo: "/project-logos/conversionlens.svg",
  },
  {
    id: "smartclinic",
    title: "SmartClinic",
    category: "fullstack",
    categoryLabel: "BACKEND · ODOO MODULE",
    year: "2026",
    description:
      "An Odoo clinic-management module for patient records, doctor availability, public bookings, and appointment tracking.",
    stack: ["Python", "Odoo 17", "PostgreSQL", "XML", "QWeb"],
    features: [
      "Patient, doctor, and appointment models",
      "Public doctor listing, booking, and status lookup",
      "Appointment-overlap checks and company-scoped rules",
    ],
    sourceUrl: "https://github.com/Suraj1812/SmartClinic",
    icon: "/artwork/backend-database.png",
    diagram: ["Doctor availability", "Book appointment", "Track status"],
    demoNote: "Source available · requires Odoo",
  },
  {
    id: "nexus-store",
    title: "Nexus Store",
    category: "fullstack",
    categoryLabel: "FULL-STACK · COMMERCE PLATFORM",
    year: "2025",
    description:
      "A commerce application combining a customer storefront, administrative catalogue tools, and a NestJS service layer.",
    stack: ["Next.js", "React", "TypeScript", "NestJS", "Prisma", "PostgreSQL"],
    features: [
      "Product, SKU, pricing, and inventory models",
      "Cart operations, stock checks, and coupon handling",
      "Administrative product and catalogue management",
    ],
    sourceUrl: "https://github.com/Suraj1812/Nexus-Store",
    icon: "/artwork/cloud-files.png",
    diagram: ["Browse catalogue", "Manage cart", "Administer products"],
    demoNote: "Source available",
    logo: "/project-logos/nexus-store.png",
  },
];

export const experience = [
  {
    company: "NEXUS SP Solutions",
    role: "Full-Stack Developer",
    type: "Freelance",
    period: "Dec 2025 — Present",
    start: { year: 2025, month: 12 },
    summary:
      "Full-stack commerce platforms, REST APIs, and AI automation for product recommendations and customer interaction.",
    details: [
      "Next.js, NestJS, and PostgreSQL platforms serving 1K+ monthly users",
      "Database and API optimization reducing response time by approximately 35%",
      "AI-based automation workflows for product and customer experiences",
    ],
    stack: ["Next.js", "NestJS", "PostgreSQL", "AI automation"],
  },
  {
    company: "Evtaar",
    role: "Software Engineer",
    type: "Remote",
    period: "Jun 2025 — Jan 2026",
    start: { year: 2025, month: 6 },
    end: { year: 2026, month: 1 },
    summary:
      "React frontend systems and concurrent Go backend services, with a focus on application performance.",
    details: [
      "React frontend and Go backend development",
      "Code splitting and optimizations improving frontend load time by 30%",
      "Concurrent services handling multiple requests",
    ],
    stack: ["React", "Go", "Performance optimization"],
  },
  {
    company: "People Maketh",
    role: "Full Stack Engineer",
    type: "Remote",
    period: "Aug 2023 — May 2025",
    start: { year: 2023, month: 8 },
    end: { year: 2025, month: 5 },
    summary:
      "End-to-end client applications, third-party integrations, and database design across multiple business domains.",
    details: [
      "Full-stack application delivery and third-party API integrations",
      "Structured backend architecture and database design",
      "Client projects across different business domains",
    ],
    stack: ["Full-stack development", "REST APIs", "Database design"],
  },
  {
    company: "Encrobytes",
    role: "Frontend Developer Intern",
    type: "On-site",
    period: "Feb 2023 — Jul 2023",
    start: { year: 2023, month: 2 },
    end: { year: 2023, month: 7 },
    summary:
      "Responsive interface components and consistent layouts, built in collaboration with designers.",
    details: [
      "HTML, CSS, and JavaScript interface components",
      "UI consistency and design bug fixes across pages",
      "Implementation of designer-provided layouts",
    ],
    stack: ["HTML", "CSS", "JavaScript"],
  },
];

export const skillGroups = [
  {
    title: "AI & automation",
    description:
      "Language model integrations, retrieval workflows, and agent tooling.",
    skills: [
      "LLM integration",
      "OpenAI APIs",
      "Ollama",
      "RAG systems",
      "LangChain",
      "Prompt engineering",
      "AI chatbots",
      "Automation workflows",
      "AI agents",
    ],
  },
  {
    title: "Frontend & product",
    description:
      "Typed interfaces, reusable components, and responsive applications.",
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "React Native",
      "Angular",
      "Tailwind CSS",
      "Redux",
      "GSAP",
      "Framer Motion",
      "Three.js",
    ],
  },
  {
    title: "Backend & APIs",
    description:
      "Service layers, real-time events, and application integrations.",
    skills: [
      "Node.js",
      "NestJS",
      "Go",
      "Python",
      "FastAPI",
      "Django",
      "Express",
      ".NET Core",
      "REST APIs",
      "Socket.IO",
    ],
  },
  {
    title: "Data & engineering",
    description:
      "Database-backed systems and Linux container deployment, with shell startup scripts and Nginx proxy configuration.",
    skills: [
      "PostgreSQL",
      "MongoDB",
      "MySQL",
      "SQLite",
      "SQLAlchemy",
      "Docker",
      "Linux containers",
      "Shell scripts",
      "Nginx",
      "Firebase",
      "Git",
    ],
  },
];
